/** Generated text from https://www.lipsum.com/ */
const lipsumSource = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac mattis tortor. Vivamus vitae elit venenatis, consectetur est a, sagittis dolor. Proin sed ligula luctus, vestibulum ante sed, congue neque. Aliquam hendrerit lorem enim, ut semper dui condimentum nec. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas tristique pretium posuere. Quisque porttitor tristique erat, vitae ornare leo lacinia blandit. Curabitur imperdiet pharetra felis, nec dapibus ante tincidunt sit amet. Etiam mollis, elit id feugiat finibus, tortor justo tincidunt libero, quis molestie tellus quam id odio. Pellentesque id velit finibus, condimentum mauris et, egestas lorem.
Aenean eget ullamcorper mi, id imperdiet ipsum. Curabitur nibh felis, elementum sed ullamcorper ac, interdum et mi. Fusce dictum aliquet lacus vel lacinia. Suspendisse et volutpat purus. Integer sed purus id velit malesuada elementum. Proin aliquet venenatis risus, sed bibendum enim accumsan sed. Quisque dignissim tincidunt ex a posuere. Sed rutrum molestie magna, at malesuada ipsum sagittis non.
Proin at nunc enim. Mauris tristique purus ut velit rhoncus, ac suscipit lorem molestie. Mauris in maximus libero. Suspendisse luctus id diam quis placerat. Aenean et turpis rhoncus, pellentesque justo ac, egestas eros. Integer eu sodales turpis. Phasellus bibendum arcu ac dolor interdum, sed sodales eros gravida. Ut gravida nisl non tellus pretium faucibus. Etiam pretium eros consectetur, posuere libero at, auctor velit. Vivamus quis lorem in turpis consectetur ultrices sed nec erat. Curabitur a diam egestas, pulvinar erat ullamcorper, viverra mi. Sed lacus nibh, faucibus a enim non, dapibus iaculis sem. Maecenas augue ex, luctus a diam ultrices, ullamcorper ultrices nunc. Phasellus sit amet bibendum ligula. Etiam pharetra vulputate diam, et imperdiet velit interdum in.
Fusce dolor felis, bibendum nec ligula id, dignissim pretium sapien. Aliquam dapibus blandit nunc in rutrum. Duis molestie lacinia justo nec scelerisque. Ut laoreet molestie nisi, non pharetra erat accumsan et. Sed nibh eros, iaculis id mattis non, tempor finibus enim. Curabitur id tortor risus. Donec porta eros sed diam vulputate, in luctus mauris eleifend. In finibus quis libero vitae interdum. Cras urna urna, convallis vitae malesuada vel, mattis id nisl. Donec ligula mi, laoreet ut blandit vel, efficitur eget justo. Sed eget velit vitae tortor posuere aliquet. Aliquam molestie enim et ipsum pellentesque rutrum. Mauris scelerisque, sem ac placerat commodo, ante orci mollis leo, quis dictum mi velit eu elit. Praesent in mollis ex. Duis ullamcorper est risus, ac vehicula purus vulputate quis. Proin hendrerit nunc tincidunt aliquet tempor.
Pellentesque sed ex tortor. Aenean magna sapien, eleifend sed ante ac, sollicitudin fermentum lacus. Vestibulum ut ex ut est varius varius. Fusce auctor volutpat felis nec eleifend. Curabitur varius eu nibh vitae sagittis. Maecenas condimentum, enim eget pulvinar pharetra, purus arcu maximus odio, et malesuada felis elit et mi. In sit amet massa sed tortor ultrices faucibus a sed justo. Sed est tortor, convallis condimentum lacus eget, eleifend aliquam risus. Cras tortor turpis, scelerisque a risus id, lobortis aliquam turpis. Duis nec lacus non nisl posuere imperdiet. Morbi venenatis sagittis ornare.
Fusce vestibulum massa et nibh finibus, a dignissim neque tincidunt. Donec nibh dui, eleifend vitae nisi eu, fermentum pulvinar diam. Aliquam consequat tortor at orci hendrerit, ac rutrum arcu maximus. Cras dictum metus vel orci rhoncus, id ullamcorper leo mollis. Duis ultricies laoreet tortor, non luctus dolor bibendum nec. Morbi a lectus consequat, aliquet ex pellentesque, rutrum eros. Nam a interdum enim. Sed rutrum elit orci. Aliquam ipsum enim, fermentum eget pellentesque nec, dignissim luctus dolor. Duis convallis leo a ex faucibus, vitae maximus massa vestibulum. Integer semper eget justo elementum laoreet. Cras pellentesque, risus eu finibus fermentum, erat nisl varius justo, non bibendum dolor sapien ac eros. Quisque ac arcu id sapien consectetur pretium. Maecenas a sem nisi.
Integer interdum laoreet finibus. Etiam quis ante varius, pharetra dolor vel, cursus neque. Fusce porta suscipit tortor, id suscipit massa condimentum in. Praesent egestas vitae tellus quis posuere. Nullam a orci neque. Maecenas ac nisi non enim ultricies ultricies. Donec vitae ligula sed ligula mattis convallis non non ligula. Suspendisse mauris mi, convallis ut consequat quis, molestie ac ligula. Sed at laoreet felis. Mauris lobortis, risus et suscipit mattis, neque dolor euismod nisi, vitae mollis dolor purus ut mauris. Sed sagittis efficitur mauris, sit amet imperdiet lectus bibendum at. Maecenas vitae tincidunt orci.
Curabitur ac metus pulvinar, auctor turpis non, rhoncus arcu. Donec non ex commodo lorem facilisis elementum. Duis vitae tincidunt leo, eget posuere eros. In ut congue diam, vitae euismod mauris. Donec tempus semper mi, ac finibus lorem egestas vel. Sed commodo elit tempor arcu egestas, sit amet pretium ex bibendum. Praesent eu tincidunt arcu. Quisque id ex neque. Aliquam volutpat ligula eget nunc luctus commodo nec vitae nibh. Nunc lacinia ornare magna quis placerat. Quisque a tincidunt lectus. Suspendisse luctus ante nec nulla facilisis pellentesque. Donec eu est mattis ante finibus placerat. Maecenas nec arcu sed purus porta viverra a sit amet purus. Nullam et velit eget enim fermentum cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Nunc posuere nisi et lorem dignissim, sit amet porta est lacinia. Ut ut maximus arcu. Maecenas eu finibus dui. Etiam tincidunt egestas nisl, vitae commodo turpis rutrum eu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec ultrices massa, sed consequat erat. Suspendisse iaculis varius velit vitae ultricies.
Nullam suscipit quam suscipit lorem varius, eu feugiat turpis luctus. Ut placerat enim eu elementum viverra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut hendrerit neque sem, mattis tristique quam auctor vel. Integer nec fermentum purus. Nunc interdum vel turpis vel ornare. Duis malesuada erat at tortor vestibulum, in hendrerit sapien lobortis. Donec dapibus, lectus in rhoncus eleifend, odio elit commodo felis, eu convallis sapien quam faucibus risus. Proin in posuere libero. Curabitur dapibus est non risus aliquam, sit amet facilisis erat lobortis. Nunc nec massa accumsan risus convallis mollis vitae ac dui. Ut nunc velit, molestie id rutrum at, iaculis quis nunc. Vivamus mattis nibh in lectus pretium efficitur. Nam aliquam dignissim sapien a commodo. Nulla dapibus sodales augue sed dictum.
Mauris pharetra, justo non varius sollicitudin, metus lectus vehicula purus, a mattis massa lectus in nunc. Vestibulum eget odio vitae magna facilisis fringilla. Etiam at pulvinar ligula. Quisque a venenatis sapien. Morbi placerat, ante et lacinia facilisis, ex felis convallis magna, facilisis dignissim diam magna eget lorem. Maecenas quis pellentesque felis. Nulla vehicula, nisl bibendum egestas ornare, est orci blandit augue, ultricies malesuada sapien elit in est. Morbi tincidunt fermentum sapien, a semper diam tristique vel. Aliquam mauris diam, gravida et hendrerit in, pellentesque ac sapien. Vivamus ultrices magna quis neque mollis, vel dictum justo eleifend. In laoreet consectetur sapien, quis scelerisque nisi posuere semper.
Duis ultrices, lorem vel posuere consequat, est quam accumsan erat, quis lacinia arcu orci eget nisl. Duis pulvinar enim sed risus pulvinar, non porta lorem euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed id ante id mauris venenatis lobortis sed quis urna. Aenean aliquam varius dui a lobortis. Quisque imperdiet pellentesque diam, gravida pharetra sem efficitur in. Ut nec nunc elementum, tristique ipsum id, volutpat dolor. Aenean vestibulum tempus facilisis. Integer id scelerisque diam, ut pretium urna.
Fusce eget erat sit amet justo pharetra gravida. Sed massa massa, eleifend nec pulvinar nec, malesuada at lacus. Nulla ultrices volutpat mauris, nec interdum eros lacinia at. Proin sed aliquam mi. Morbi molestie volutpat nisl, sit amet sagittis enim suscipit quis. Aenean imperdiet non urna sed fringilla. Vestibulum sit amet felis finibus, pulvinar lorem eu, semper sem. Cras ac ultrices erat. Nullam id quam ut augue sollicitudin convallis. Quisque porta commodo dignissim. Pellentesque in justo enim. Curabitur eget orci sem. Aenean fermentum aliquam nibh vel mollis. Integer sodales nisi ex, quis sollicitudin quam scelerisque at. Curabitur finibus erat nec sodales porta.
Suspendisse potenti. Nam dui nisi, tempor in nibh feugiat, viverra commodo eros. Nam sagittis porta erat eget viverra. Fusce orci est, suscipit at vestibulum non, vestibulum sit amet elit. Suspendisse potenti. Sed lobortis aliquet convallis. Cras nec urna neque. Phasellus id magna sem. Maecenas placerat aliquet diam non ultrices. In faucibus eu neque a ornare. In elementum augue vel leo lobortis volutpat. Morbi eleifend eros velit, non lobortis nulla eleifend at. Ut pulvinar, magna at cursus congue, odio elit mollis urna, quis suscipit arcu tortor eget augue. Aenean lobortis tellus porta, vulputate urna at, cursus metus.
Aenean tempus, massa eu faucibus blandit, tellus ipsum pretium mauris, quis finibus nisl ex iaculis ante. Curabitur ornare ac nulla sit amet tincidunt. Pellentesque maximus consectetur ornare. Donec pulvinar nunc est, eu condimentum sem vestibulum at. Nulla egestas quam ut elit tempor, vitae eleifend libero pulvinar. Mauris a tristique lacus. Nunc cursus mi at odio hendrerit, in auctor lectus auctor. Cras euismod sit amet neque sed ornare. Sed mollis, diam eu efficitur porta, nisi mauris posuere est, non fringilla dolor justo sit amet nunc.
Sed tortor neque, pellentesque posuere laoreet nec, rutrum sed mauris. Integer vel sollicitudin orci. Vivamus condimentum lorem quis turpis luctus consequat. Cras non accumsan elit. Suspendisse at commodo est. Maecenas pellentesque arcu in tellus fermentum, vitae interdum urna facilisis. Maecenas sed luctus sapien. Morbi malesuada, magna a pellentesque sollicitudin, odio massa blandit leo, posuere elementum arcu diam eget purus. Aliquam rutrum leo ac orci bibendum pellentesque. Maecenas auctor nunc sit amet lorem rhoncus, id placerat metus mattis.
Aliquam bibendum eros eget commodo fermentum. Pellentesque vel leo fringilla, auctor nunc eget, iaculis sem. Pellentesque in libero sed nunc vestibulum suscipit et id lectus. Nullam nec lorem ac lectus dictum maximus ac hendrerit nisi. Proin ut neque pellentesque, lobortis justo in, varius purus. Etiam lacinia orci tincidunt, gravida augue sed, venenatis mauris. Cras ut diam risus. Suspendisse aliquet enim id velit viverra tincidunt. Maecenas in malesuada risus, sed pretium tortor. Phasellus mollis ut lectus sit amet auctor. Etiam in accumsan neque.
Ut quis tellus in elit malesuada tincidunt. Praesent sollicitudin dolor imperdiet, tincidunt erat sed, aliquam odio. Cras fermentum ac nibh hendrerit tristique. Pellentesque volutpat ante quis ante rutrum aliquet. Praesent gravida massa mauris, vitae interdum erat semper sit amet. In imperdiet malesuada augue, ac aliquet nisl tincidunt et. Nulla id vehicula dolor. Suspendisse ultrices ante sed luctus rhoncus. Integer tempor ex cursus felis semper, id tincidunt ligula fermentum. Nunc sodales nisl et diam viverra, vitae tristique sapien accumsan. In sollicitudin nulla id sapien mollis malesuada. Nulla facilisi. Nulla sagittis venenatis leo sit amet interdum. Curabitur commodo ornare magna, eu congue leo sollicitudin et. Curabitur pretium rutrum urna vel mollis.
Mauris tempor, diam at tristique pulvinar, mauris felis ultrices nibh, et accumsan nibh tellus eu ipsum. Nam commodo ornare magna id semper. Donec vestibulum congue elit, vel egestas metus vestibulum vitae. Etiam tortor urna, suscipit a bibendum quis, mollis in tortor. Aliquam sem orci, elementum eget purus iaculis, cursus porttitor nibh. Nullam id nibh ac nisl venenatis venenatis. Vivamus pulvinar enim blandit nulla tristique consequat.
Pellentesque accumsan nec velit in venenatis. Integer ornare dapibus sem. Nulla semper tempor sapien, non varius enim scelerisque sed. Sed cursus erat ac luctus pharetra. Donec tempor varius nisi. Nulla facilisi. Donec viverra dapibus dui ut finibus. Duis turpis nunc, tincidunt accumsan ex a, accumsan lobortis sapien. Nulla eget justo nec ipsum ornare feugiat nec a ligula.
Suspendisse lectus risus, rutrum sed sem eget, aliquam faucibus nisl. Nunc vulputate vestibulum lectus a sollicitudin. Cras in condimentum libero. Suspendisse cursus rutrum lorem, id commodo ligula pellentesque eget. Nunc interdum purus eget tellus fringilla blandit. Donec ac dapibus erat. Cras libero augue, congue sed gravida sed, egestas egestas purus. Nunc placerat, massa sed imperdiet tempor, magna nisi tincidunt dolor, et posuere diam magna id risus. Suspendisse quis feugiat elit, ut maximus diam. Aenean tempus tortor ligula, a aliquet metus commodo nec. Nunc a leo dui. Pellentesque id mi tortor. Quisque aliquam, orci at dapibus efficitur, nulla tortor ullamcorper velit, nec tincidunt nisl sem et felis. Phasellus non nunc vestibulum, congue nunc id, consectetur neque. Vivamus et dolor quis lacus vestibulum iaculis vitae vehicula enim.
Suspendisse quis justo sem. Donec pulvinar libero sed dui vulputate, vel ullamcorper massa vulputate. Pellentesque vulputate, ligula nec gravida lobortis, nibh lacus euismod dolor, sit amet dignissim ante odio ac lorem. Sed quis purus nec diam fringilla ultricies. Mauris luctus sapien nec commodo malesuada. Duis in rutrum massa, non tincidunt eros. Proin risus turpis, vehicula at cursus nec, volutpat sit amet ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis et risus id venenatis. Sed lectus nibh, ultricies suscipit mattis lobortis, suscipit et felis. Pellentesque sodales, tellus sit amet volutpat rhoncus, quam eros dignissim ipsum, nec vestibulum metus orci id metus. Mauris condimentum sem sed efficitur suscipit. Suspendisse posuere risus eu arcu varius, et euismod odio tincidunt. Suspendisse at consequat erat. Maecenas nec diam vel mauris tincidunt mollis id vel purus.
Suspendisse potenti. Phasellus pharetra, lacus sed iaculis efficitur, odio metus vestibulum lectus, vitae pulvinar lacus risus vel nibh. Proin eget nunc semper lectus sollicitudin semper eu et libero. Pellentesque euismod sit amet ligula quis elementum. Maecenas sed magna congue, mollis tellus at, commodo eros. Quisque ornare risus ex, vel fringilla lacus laoreet vitae. Suspendisse auctor elit eget nulla tincidunt, non finibus ligula varius. Mauris ultricies, enim non placerat sollicitudin, velit lorem commodo quam, ut pharetra lorem enim sit amet leo. Sed molestie orci vitae libero elementum, imperdiet gravida quam pulvinar. Vivamus pharetra accumsan tristique. Duis mollis augue sit amet libero sagittis, vitae commodo nunc tristique. Nullam eu lobortis mauris, quis volutpat turpis. Pellentesque eu ornare tortor. Suspendisse vulputate ipsum massa, at blandit orci rutrum pretium. Vestibulum laoreet metus a hendrerit fringilla. Donec ut tortor in mauris tristique luctus eget ac purus.
Maecenas efficitur libero cursus dui ullamcorper, at laoreet ex convallis. Pellentesque imperdiet auctor euismod. Sed sed ante sollicitudin, consectetur turpis a, lacinia justo. Mauris at convallis sapien. Nunc lectus odio, maximus a imperdiet sodales, tempor id sapien. Phasellus commodo lacinia justo eget vestibulum. Integer faucibus ipsum eget arcu dictum, molestie faucibus metus ultricies. Quisque dolor est, mattis sit amet odio volutpat, lobortis sollicitudin nisl.
Aenean et tellus vel massa ultricies sagittis. Phasellus in lacus orci. Nullam quis maximus lacus, porta porta urna. Aliquam placerat aliquam dolor, non blandit est sagittis a. Aliquam molestie ipsum vel neque convallis posuere. Morbi ultrices dui vel quam dictum, quis interdum lacus gravida. Sed euismod dui sit amet velit imperdiet rutrum. Curabitur rutrum quam non dolor feugiat dignissim. Vestibulum tristique vitae turpis cursus faucibus. Aenean fermentum porttitor tortor, et tempus leo pharetra sit amet.
Aliquam in est eleifend, porta nisl id, porttitor neque. Integer vel vehicula turpis. Vivamus vel enim placerat leo ornare viverra. Pellentesque vestibulum rutrum luctus. Cras imperdiet eu felis nec malesuada. Ut laoreet a dui at sagittis. Proin porttitor, lacus eu convallis vestibulum, lorem arcu ornare lectus, dictum feugiat tellus turpis at ex. Quisque malesuada vitae mi molestie consequat. Nulla dapibus tellus sit amet erat pretium, in dictum lacus pellentesque.
Nunc bibendum posuere malesuada. Pellentesque tincidunt quam libero, vestibulum pulvinar est hendrerit et. In iaculis lacus non dui lobortis, sit amet cursus libero facilisis. Curabitur luctus leo metus. Nulla venenatis ut lorem id dapibus. Donec consectetur sed nibh non accumsan. Maecenas varius efficitur suscipit.
Nullam maximus sem at mauris porttitor suscipit. Nunc placerat nisl sed mi viverra dictum. Nam commodo lacus et lorem vestibulum luctus. Curabitur consequat venenatis mi, id finibus nisl consequat quis. Morbi blandit efficitur magna, et facilisis urna tristique vel. Praesent accumsan est vel elementum sagittis. Vestibulum vulputate ultricies mollis. Curabitur vel libero malesuada, porttitor eros ac, pulvinar ex. Donec ante augue, egestas quis molestie eget, imperdiet vitae mauris. Etiam nec massa nec nisi scelerisque pharetra. Proin convallis, mauris et vestibulum iaculis, orci nisl iaculis arcu, vel vestibulum erat felis at magna.
Cras scelerisque tellus est, eu rutrum purus semper sit amet. Nam a mauris quis tortor lacinia rutrum sed a elit. Nam nisl orci, condimentum sit amet sapien eget, sagittis sagittis augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras ultricies tincidunt arcu sed auctor. Phasellus efficitur, elit at cursus accumsan, justo turpis aliquam lectus, a sollicitudin mauris est vitae metus. Proin eget egestas urna. Praesent facilisis sem non malesuada convallis. Fusce commodo arcu varius libero rhoncus, in auctor magna varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla a sem rhoncus, luctus leo id, bibendum libero. Aenean imperdiet, libero scelerisque tristique accumsan, dui orci ultrices nibh, at tempor lorem neque vitae ligula. Sed placerat fermentum posuere. Duis malesuada purus dui, a rutrum orci dapibus a. Proin sit amet ultrices dolor, non convallis nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
Aenean accumsan felis magna, ut varius turpis posuere nec. Pellentesque hendrerit nec tortor id tempus. Curabitur facilisis magna efficitur mollis posuere. Maecenas dictum, mauris vitae accumsan porta, tortor libero consectetur eros, sit amet vehicula dolor elit in lorem. Sed commodo faucibus dui, sed rhoncus nisl venenatis eu. Duis eget ullamcorper justo, in dictum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit.`;

const lipsumParas = lipsumSource.split('\n');
const lipsumSentences = lipsumParas.flatMap((p) => p.split('. ')).map((s) => `${s}.`);

/**
 * Generates placeholder Lorem Ipsum text.
 *
 * @param count Number of sentences or paragraphs to generate.
 * @param type Whether to generate sentences or paragraphs.
 * @param format Maps generated sentences or paragraphs to JSX elements. If undefined, this function generates a raw string.
 * @returns An array of elements if `format` is provided, otherwise, a string.
 */
export function Lipsum(
  count: number,
  type: 'sentences' | 'paragraphs',
  format?: (str: string) => JSX.Element,
): JSX.Element[] | string {
  if (count <= 0) {
    return '';
  }

  const sourceArray: string[] = type === 'paragraphs' ? lipsumParas : lipsumSentences;
  const strings: string[] = [];
  for (let i = 0; i < count; i++) {
    // Grab the requested number of items, looping around the end of the source array.
    strings.push(sourceArray[i % sourceArray.length]);
  }

  if (format) {
    return strings.map((s) => format(s));
  } else {
    return strings.join(type === 'paragraphs' ? '\n\n' : ' ');
  }
}
